/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CA2;

/**
 *
 * @author leong
 */

/**
 * Class: DIT/FT/1B/02 
 * Name: Leong Yu Zhi Andy 
 * Admission Number: P2205865
 * @author leong
 */

import javax.swing.JOptionPane;

import java.util.ArrayList;

import java.security.*;

import java.io.IOException;

import javax.swing.table.DefaultTableModel;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    //on load
    public GUI() {
        initComponents();
        try {

            rental = new RentalSystem();

            comicArr = rental.getComicArr();
            renteeArr = rental.getRenteeArr();

            comicPage = 1;
            renteePage = 1;

            //Setting comic and rentee max pages
            comicPages = comicArr.size();
            renteePages = renteeArr.size();
            //Settig Comic Data
            displayComic();

            //Setting Rentee Data
            displayRentee();
        } catch (Exception e) {
            System.out.println(e.getStackTrace());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchRadio = new javax.swing.ButtonGroup();
        comicPanel = new javax.swing.JPanel();
        titleField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        isbnField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rentalField = new javax.swing.JTextField();
        depositField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        comicInfo = new javax.swing.JTextArea();
        comicPrev = new javax.swing.JButton();
        comicNext = new javax.swing.JButton();
        comicLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        renteeID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        renteeName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        loanData = new javax.swing.JTable();
        renteePrev = new javax.swing.JButton();
        renteeNext = new javax.swing.JButton();
        renteeLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sout = new javax.swing.JTextArea();
        getStat = new javax.swing.JButton();
        clearSOUT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        comicSearch = new javax.swing.JRadioButton();
        renteeSearch = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        searchIn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        endBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        comicPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        titleField.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ISBN-13:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Title:");

        isbnField.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Daily Rental Cost:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Deposit:");

        rentalField.setEditable(false);

        depositField.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Additional Information:");

        comicInfo.setEditable(false);
        comicInfo.setColumns(20);
        comicInfo.setRows(5);
        jScrollPane2.setViewportView(comicInfo);

        comicPrev.setText("Previous");
        comicPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comicPrevActionPerformed(evt);
            }
        });

        comicNext.setText("Next");
        comicNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comicNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comicPanelLayout = new javax.swing.GroupLayout(comicPanel);
        comicPanel.setLayout(comicPanelLayout);
        comicPanelLayout.setHorizontalGroup(
            comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comicPanelLayout.createSequentialGroup()
                        .addGroup(comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentalField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(55, 55, 55)
                        .addGroup(comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(comicPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(comicPanelLayout.createSequentialGroup()
                                .addComponent(depositField)
                                .addContainerGap())))
                    .addGroup(comicPanelLayout.createSequentialGroup()
                        .addGroup(comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(comicPanelLayout.createSequentialGroup()
                                .addGroup(comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isbnField)
                                    .addComponent(titleField)))
                            .addGroup(comicPanelLayout.createSequentialGroup()
                                .addComponent(comicPrev)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comicNext)))
                        .addContainerGap())))
        );
        comicPanelLayout.setVerticalGroup(
            comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(isbnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rentalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(comicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comicPrev)
                    .addComponent(comicNext))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        comicLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comicLabel.setText("Comic");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Member-ID:");

        renteeID.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Name:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("List of Loans:");

        renteeName.setEditable(false);

        loanData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN-13", "Title", "Rental per Day", "Deposit Fee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(loanData);
        if (loanData.getColumnModel().getColumnCount() > 0) {
            loanData.getColumnModel().getColumn(0).setResizable(false);
            loanData.getColumnModel().getColumn(0).setPreferredWidth(1);
            loanData.getColumnModel().getColumn(1).setResizable(false);
            loanData.getColumnModel().getColumn(1).setPreferredWidth(100);
            loanData.getColumnModel().getColumn(2).setResizable(false);
            loanData.getColumnModel().getColumn(2).setPreferredWidth(1);
            loanData.getColumnModel().getColumn(3).setResizable(false);
            loanData.getColumnModel().getColumn(3).setPreferredWidth(1);
        }

        renteePrev.setText("Previous");
        renteePrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renteePrevActionPerformed(evt);
            }
        });

        renteeNext.setText("Next");
        renteeNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renteeNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(renteeID)
                            .addComponent(renteeName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(renteePrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(renteeNext)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(renteeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(renteeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(renteePrev)
                    .addComponent(renteeNext))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        renteeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        renteeLabel.setText("Rentee");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        sout.setEditable(false);
        sout.setColumns(20);
        sout.setRows(5);
        jScrollPane1.setViewportView(sout);

        getStat.setBackground(new java.awt.Color(0, 0, 153));
        getStat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getStat.setForeground(new java.awt.Color(255, 255, 255));
        getStat.setText("Get Earning Stats");
        getStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStatActionPerformed(evt);
            }
        });

        clearSOUT.setBackground(new java.awt.Color(0, 0, 153));
        clearSOUT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearSOUT.setForeground(new java.awt.Color(255, 255, 255));
        clearSOUT.setText("Clear Message");
        clearSOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSOUTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(getStat, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(clearSOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearSOUT, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(getStat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        searchBtn.setBackground(new java.awt.Color(0, 153, 51));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchRadio.add(comicSearch);
        comicSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comicSearch.setText("Comic by ISBN-13");
        comicSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comicSearchActionPerformed(evt);
            }
        });

        searchRadio.add(renteeSearch);
        renteeSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        renteeSearch.setSelected(true);
        renteeSearch.setText("Rentee by MemberID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Search:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(comicSearch)
                        .addGap(44, 44, 44)
                        .addComponent(renteeSearch))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(searchIn, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comicSearch)
                    .addComponent(renteeSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(searchIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Search");

        endBtn.setBackground(new java.awt.Color(255, 0, 0));
        endBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        endBtn.setForeground(new java.awt.Color(255, 255, 255));
        endBtn.setText("Save & Exit");
        endBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("System Message");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Comic Rental System");

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Admin Panel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comicLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(renteeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(endBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comicLabel)
                    .addComponent(renteeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endBtnActionPerformed
        try {
            //Export and close program
            IO.export(comicArr, renteeArr, adminArr);
            JOptionPane.showMessageDialog(
                    null,
                    "Saving data...",
                    "Message",
                    JOptionPane.INFORMATION_MESSAGE
            );
            JOptionPane.showMessageDialog(
                    null,
                    "Thank you for using Comic Rental.\nWe look forward to serve you in the future.",
                    "Message",
                    JOptionPane.INFORMATION_MESSAGE
            );
            System.exit(0);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_endBtnActionPerformed

    private void comicSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comicSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comicSearchActionPerformed

    private void comicPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comicPrevActionPerformed
        try {
            if (!(comicPage - 1 < 1)) {
                comicPage -= 1;
                displayComic();
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_comicPrevActionPerformed
    //Function to rerender/re display the comic data fields
    public void displayComic() {
        try {
            rental.importComics();
            //Bunch of set text
            
            comicArr = rental.getComicArr();
            comicPages = comicArr.size();
            comicLabel.setText(String.format("Comic %d of %d", comicPage, comicPages));
            if (comicPages == 0){
                return;
            }
            isbnField.setText(comicArr.get(comicPage - 1).getISBN());
            titleField.setText(comicArr.get(comicPage - 1).getTitle());
            rentalField.setText(String.format("$%.2f", (comicArr.get(comicPage - 1).getCost() / 20.0)));
            depositField.setText(String.format("$%.2f", (comicArr.get(comicPage - 1).getCost() * 1.10)));
            if (comicArr.get(comicPage - 1).getType().equals("Comic")) {
                comicInfo.setText("This is a Comic in English");
            } else {
                if (comicArr.get(comicPage - 1).getLanguage().equals("EN")) {
                    comicInfo.setText("This is a Manga translated to English ");
                } else {
                    comicInfo.setText("This is a Manga in Japanese");
                }

            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }
    
    //Function to rerender/re display the rentee data fields

    private void displayRentee() {
        try {
            rental.importRentee();
            renteeArr= rental.getRenteeArr();
            renteePages = renteeArr.size();

            renteeLabel.setText(String.format("Rentee %d of %d", renteePage, renteePages));
            if(renteePages == 0){
                return;
            }
            
            renteeID.setText(renteeArr.get(renteePage - 1).getMemberID());
            renteeName.setText(renteeArr.get(renteePage - 1).getName());

            DefaultTableModel model = (DefaultTableModel) loanData.getModel();
            int rowCount = model.getRowCount();
            //Remove rows 1 by 1 based on the size
            for (int i = rowCount - 1; i >= 0; i--) {
                model.removeRow(i);
            }
            
            for (Comic comic : renteeArr.get(renteePage - 1).getComics()) {
                //For every comic in rentee, add new row into the table
                String[] rowData = {
                    comic.getISBN(),
                    comic.getTitle(),
                    String.format("$%.2f", (comic.getCost() / 20.0)),
                    String.format("$%.2f", (comic.getCost() * 1.10))

                };
                model.addRow(rowData);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    private void comicNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comicNextActionPerformed
        //next comic details page
        try {
            if (!(comicPage + 1 > comicPages)) {
                comicPage += 1;
                displayComic();
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_comicNextActionPerformed

    private void renteePrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renteePrevActionPerformed
        //prev rentee details page IF page != 1
        try {
            if (renteePage != 1) {

                renteePage -= 1;
                displayRentee();
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_renteePrevActionPerformed

    private void renteeNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renteeNextActionPerformed
        //Next rentee details page 
        try {
            if (renteePage != renteePages) {
                renteePage += 1;
                displayRentee();
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_renteeNextActionPerformed

    private void getStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStatActionPerformed
        //Get earning stats
        sout.setText(rental.getEarning());
    }//GEN-LAST:event_getStatActionPerformed

    private void clearSOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSOUTActionPerformed
        //Clear system message
        sout.setText("");
    }//GEN-LAST:event_clearSOUTActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        //Search button
        String in = searchIn.getText();
        if (renteeSearch.isSelected()) {
            //Search member ID
            boolean flag = false;
            int index = 1;
            //Loop through the rentee Array, if rentee member id is in array, store the index to set the rentee page
            for (Rentee renteeArr1 : renteeArr) {
                if ((renteeArr1).getMemberID().equals(in)) {
                    flag = true;
                    break;
                }
                index++;
            }

            if (!flag) {
                sout.setText(String.format("No Such Member ID \"%s\" in the data!", in));
            } else {
                sout.setText("Found and displayed rentee with the Member ID: " + in);
                renteePage = index;
                displayRentee();
            }
        } else {
            //Search ISBN
            int index = 1;
            boolean flag = false;
            //Search the comic array if comic ISBN-13 is in array, if id in array,store the idex to set the comic page
            for (Comic i : comicArr) {
                if (i.getISBN().equals(in)) {
                    flag = true;
                    break;
                }
                index++;
            }

            if (flag) {
                sout.setText("Found and displayed item with the ISBN-13:" + in);
                comicPage = index;
                displayComic();
            } else {
                sout.setText(String.format("No Such ISBN-13 \"%s\" in the data!", in));

            }
        }

    }//GEN-LAST:event_searchBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    //Rerender when window is focused/clicked
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        displayComic();
        displayRentee();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, NoSuchAlgorithmException, ClassNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);

            }
        });

    }
    private RentalSystem rental;
    private int comicPage;
    private int renteePage;
    private int comicPages;
    private int renteePages;
    private ArrayList<Manga> mangaArr;
    private ArrayList<Comic> comicArr;
    private ArrayList<Administrator> adminArr;
    private ArrayList<Rentee> renteeArr;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearSOUT;
    private javax.swing.JTextArea comicInfo;
    private javax.swing.JLabel comicLabel;
    private javax.swing.JButton comicNext;
    private javax.swing.JPanel comicPanel;
    private javax.swing.JButton comicPrev;
    private javax.swing.JRadioButton comicSearch;
    private javax.swing.JTextField depositField;
    private javax.swing.JButton endBtn;
    private javax.swing.JButton getStat;
    private javax.swing.JTextField isbnField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable loanData;
    private javax.swing.JTextField rentalField;
    private javax.swing.JTextField renteeID;
    private javax.swing.JLabel renteeLabel;
    private javax.swing.JTextField renteeName;
    private javax.swing.JButton renteeNext;
    private javax.swing.JButton renteePrev;
    private javax.swing.JRadioButton renteeSearch;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchIn;
    private javax.swing.ButtonGroup searchRadio;
    private javax.swing.JTextArea sout;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
